# Generated by Django 4.2.6 on 2023-11-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_birthdate',
            field=models.DateField(blank=True, verbose_name='user_birthdate'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='user_sex',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
    ]
