# Generated by Django 4.2.6 on 2023-11-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appuser_user_birthdate_alter_appuser_user_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='user_birthdate',
            field=models.DateField(verbose_name='user_birthdate'),
        ),
    ]
