# Generated by Django 4.2.6 on 2023-11-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appuser_user_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='refresh_token',
            field=models.TextField(default='', verbose_name='refresh token'),
        ),
    ]
