# Generated by Django 4.2.6 on 2023-11-13 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='is_staff',
            new_name='is_stuff',
        ),
    ]
