# Generated by Django 4.2.6 on 2023-11-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_appuser_first_name_alter_appuser_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_stuff',
        ),
        migrations.AddField(
            model_name='appuser',
            name='permissions_level',
            field=models.IntegerField(default=0, verbose_name='permissions'),
        ),
    ]
