# Generated by Django 4.2.6 on 2023-12-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_card', '0008_rename_user_appdoctorcard_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('appointment_date', models.DateTimeField(verbose_name='appointment date')),
                ('state', models.CharField(choices=[('new', 'New'), ('processed', 'Processed'), ('end', 'End')], default='new', max_length=20)),
                ('comment', models.TextField(verbose_name='Comment')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_card.appdoctorcard')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_card.apppatientcard')),
            ],
            options={
                'db_table': 'doctor_appointment',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalConclusions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('disease', models.CharField(blank=True, max_length=255)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse', models.IntegerField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('conclusions', models.TextField(blank=True)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical_tools.appdoctorappointment')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
