# Generated by Django 4.2.6 on 2023-12-05 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AppDoctorCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="living_address"),
                ),
                (
                    "work_experience",
                    models.IntegerField(blank=True, verbose_name="Work Experience"),
                ),
                (
                    "appointments",
                    models.IntegerField(
                        default=0, verbose_name="Number of appointments"
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Medical degree"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Position"
                    ),
                ),
                (
                    "photo",
                    models.FilePathField(blank=True, verbose_name="Path to photo"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-work_experience"],
            },
        ),
    ]
