# Generated by Django 4.2.6 on 2023-12-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_card", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdoctorcard",
            name="photo",
            field=models.TextField(blank=True, verbose_name="Path to photo"),
        ),
    ]
