# Generated by Django 4.2.6 on 2023-12-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_card", "0002_alter_appdoctorcard_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdoctorcard",
            name="photo",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="URL to photo"
            ),
        ),
    ]
