# Generated by Django 4.2.6 on 2023-12-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_card", "0003_alter_appdoctorcard_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdoctorcard",
            name="photo",
            field=models.FileField(
                blank=True, db_column="image_url", null=True, upload_to="images/"
            ),
        ),
    ]
