# Generated by Django 4.2.6 on 2023-12-05 23:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_card", "0004_alter_appdoctorcard_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appdoctorcard",
            name="photo",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="image url"
            ),
        ),
    ]
