# Generated by Django 4.2.6 on 2023-12-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_card", "0005_alter_appdoctorcard_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="appdoctorcard",
            name="about_me",
            field=models.TextField(blank=True, verbose_name="About Me"),
        ),
    ]
