# Generated by Django 4.2.6 on 2023-12-07 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_card", "0007_alter_appdoctorcard_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appdoctorcard",
            old_name="user",
            new_name="user_id",
        ),
        migrations.RenameField(
            model_name="apppatientcard",
            old_name="user",
            new_name="user_id",
        ),
    ]
